### ISSUE TITLE
 java.lang.NoClassDefFoundError when launching on 1.12.2 server

### ISSUE THREAD

**Issue by venarium** [TheFabulousCube/Paragonia#1]
Receiving the attached error when attempting to launch a 1.12.2 server with the Beta release on Curseforge (assuming this is 0.87). Occurs when no other mods are present. Does not occur on single player. Let me know if you need any more info... thanks!

[crash-2021-04-05_19.43.30-server.txt](https://github.com/TheFabulousCube/Paragonia/files/6268886/crash-2021-04-05_19.43.30-server.txt)

**Comment by TheFabulousCube** [comment]
Wow.  Just now saw this.  We discussed it heavily in the discord.  It's a known issue with some servers.  It's been so long now, I'd have to go back and look at the issue.  It was something to do with Bit Bucket, I think.  This mod is so far behind now, I don't guess that really helps much, though.  
Sorry.
